### ISSUE TITLE
Getting a Foundation `Date` from `Value`

### ISSUE THREAD

**Issue by mcdappdev** [davedelong/time#36]
Hey there,

Thank you for this fantastic library!! Quick question that I couldn't find in the docs (hopefully I didn't just miss it). 

I need to calculate a date 5 minutes from now in UTC. Here's what I'm doing: 

```swift
let utc = Clock.system.converting(to: TimeZone(identifier: "UTC")!).thisMinute()
let plusFiveMinutes = (utc + .minutes(5)).firstInstant.date
```

I'm clear on everything up until `.firstInstant.date` - that was the only way I could find to pull a Foundation `Date` out of my addition operation. Does that seem right? 

Thank you again!

**Comment by davedelong** [comment]
Yep, this is probably correct for what you're trying to do.

[All calendar values represents _ranges_](https://github.com/davedelong/time/blob/master/Documentation/2-Usage/1-Concepts.md#calendar-values-are-ranges) of possible instants. When you're asking for "5 minutes from now", you're getting back a value that contains _all possible `Instants`_ in that 5-minute range.

Technically, _any_ `Instant` value within that range meets the criteria of "occurs five minutes from now", because your accuracy is only down to the _minute_ (because you used `.thisMinute()`).

The `firstInstant` of an absolute Value is therefore the _first_ point in time that meets the criteria of being "five minutes from now".

And then once you've got an `Instant`, you can easily convert it back to a `Foundation.Date` by using its `.date` value.

---

All this to say that yes, this is correct. 😁

**Comment by mcdappdev** [comment]
@davedelong thanks so much for the quick response! This actually helps tighten my understanding quite a bit, I think I was missing the key point about values being ranges, not singular points. Thank you!!

**Comment by ricobeck** [comment]
Thanks! That helped me a lot. 

Did I miss this in the documentation? If not I'd suggest that it should be mentioned somewhere explicitly because after reading in the docs I was under the impression that converting back to `Foundation.Date` is impossible.
