### ISSUE TITLE
All zero-argument methods that return a value should be computed properties instead

### ISSUE THREAD

**Issue by sstigler** [davedelong/time#7]
What would you think about changing the method signatures such that as a general rule, all zero-argument methods that return a value were replaced with computed properties? For example, `func now() -> Instant` would be replaced by `var now: Instant`. I think this would make code that called those methods significantly more concise and easier to read.

**Comment by davedelong** [comment]
I could be convinced of this this for things like `.yearMonth` vs `.yearMonth()`, since the value technically won't change between invocations. However, `Clock.now()` (and related methods) IMO should remain as functions because each time you call them, you can technically get different values (especially with `.now()`, which returns a new value every time you call it).

**Comment by sstigler** [comment]
Ah, interesting. I haven’t heard that argument before, that computed properties  are reserved for things that don’t change every time you call them. Is that officially documented somewhere?

**Comment by davedelong** [comment]
I'm not sure if that's documented explicitly, but my understanding is that this is a motivation for differentiating between "properties" and "methods". If I were to guess, this is a holdover from the days of C, where "properties" were really members of structs (like ivars in Objective-C), and so looking them up is and `O(1)` operation and implies that each lookup is doing the same thing. By contrast, a method is executing code, and thus can do different things each time depending on the state of the world.

I would also say that, philosophically, `now` is not a _property_ of a `Clock`, in that a `Clock` doesn't "have" a "now". However, you can *generate* a "now" by executing a method.

**Comment by davedelong** [comment]
The only real hesitation I would have about making this change is that, since the rest of Chronology's implementation is still undecided, I'm not sure I'd ever need variations on a `.hourMinute` value (as an example). For instance, let's say I decide to add a way to get a value's `HourMinute` in a different timezone... To do that, I'd probably make a `func hourMinute(in timeZone: TimeZone? = nil) → HourMinute` method. Having this method would be at odds with also having a `.hourMinute` property.

**Comment by Saklad5** [comment]
> Ah, interesting. I haven’t heard that argument before, that computed properties are reserved for things that don’t change every time you call them. Is that officially documented somewhere?

The [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/#general-conventions) encourage developers to document when computed properties involve significant computation.

Personally, I think it comes down to the usage mindset you want. If you are “doing” something, it should be a method. If you are “using” or “reading” something, it should be a computed property.

`.now` is a complicated case, with arguments for both approaches. [Foundation itself](https://developer.apple.com/documentation/foundation/date/1780165-timeintervalsincereferencedate) seems to use the computed property approach.

**Comment by davedelong** [comment]
I've made a decision on this:

If a value has a method such that _repeated_ invocations would produce the _same value_ every time, then it will be a property. If repeated invocations will produce _potentially different_ values, then it will be a method.

For example:
- `clock.today()` is a method, because repeated invocations may produce different values.
- `today.nextDay` is a property, because repeated invocations will always produce the same value.
